### ISSUE TITLE
[Bug]: User is not saved in the session after the authentication anymore

### ISSUE THREAD

**Issue by lukmzig** [pimcore/admin-ui-classic-bundle#104]
`saveUserToSession ` method is never called anymore and so user is never stored in the session. 
Previously it was set [here](https://github.com/pimcore/pimcore/blob/10.6/bundles/AdminBundle/Security/Authenticator/AdminLoginAuthenticator.php#L78)

This causes problems for example in the portal engine previews because user is always null [here](https://github.com/pimcore/portal-engine/blob/3.x/src/Service/Security/SecurityService.php#L78).

Also verify if [this](https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/src/Security/Event/LogoutListener.php#L83) is still necessary as currently the user is probably always null.

**Comment by dvesh3** [comment]
[Session is now managed by the Symfony](https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Upgrade_Notes/#sessions-) so we can simply call `Authentication::authenticateSession()` to get the current user from the session.

**Comment by dvesh3** [comment]
Fixed by #106
