### ISSUE TITLE
[Bug]: icon image path error

### ISSUE THREAD

**Issue by mhgtlc** [pimcore/admin-ui-classic-bundle#107]
Error: Uncaught ReferenceError: L is not defined

file: `public/js/pimcore/startup.js:962` 

```
L.Icon.Default.imagePath = '../bundles/pimcoreadmin/build/admin/images/';
```

**Comment by aryaantony92** [comment]
Unable to reproduce the error. It's working now

**Comment by mhgtlc** [comment]
@aryaantony92 

> Unable to reproduce the error. It's working now

The error is still there:

https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/public/js/pimcore/startup.js#L962C1-L962C3
Where does this `L` come from?

**Comment by aryaantony92** [comment]
@mhgtlc Could you please try again with the latest version ?

**Comment by dvesh3** [comment]
@aryaantony92 @mhgtlc `L.` is a [leaflet object](https://github.com/pimcore/admin-ui-classic-bundle/blob/328928e0bd66ea549c2fd962036bd2c2a605c49f/public/assets/admin.js#L5) (used mainly for Geo datatypes). I'm wondering why this is not part of admin bundle? 🤔

**Comment by aryaantony92** [comment]
https://github.com/pimcore/admin-ui-classic-bundle/blob/8846027e49027d124fcccf9b73f8e1040c18ebbf/public/js/pimcore/startup.js#L962 This is in the admin bundle.

**Comment by storbahn** [comment]
I still have this error L.Icon.Default.imagePath = '../bundles/pimcoreadmin/build/admin/images/'; (js error in browser console)

We use the pimcore version 11.1.5 and the admin bundle with version 1.3.4

**Comment by aarongerig** [comment]
Same here. I get a `L is not defined` error in the console, when loading the Pimcore Backend.

@dvesh3 This issue should be re-opened as it doesn't seem to be fixed, right?

**Comment by aarongerig** [comment]
@dvesh3 WDYT? 🙂

**Comment by sevarozh** [comment]
I can also confirm it with:
- pimcore/pimcore 11.1.4
- pimcore/admin-ui-classic-bundle 1.3.1


It looks like the "Leaflet" library is loaded **later** than L.Icon.Default.imagePath is called in startup.js.
After loading of admin, L is defined in console:
![Bildschirmfoto 2024-03-28 um 11 37 49](https://github.com/pimcore/admin-ui-classic-bundle/assets/5694627/1b326f12-5ac7-4df3-905c-651be7611a14)

Issue is closed, but I can't find a commit with a bug fix @aryaantony92

**Comment by mhgtlc** [comment]
@brusch @dvesh3 @aryaantony92 
Issue is still there:
- pimcore/pimcore 11.2.2
- pimcore/admin-ui-classic-bundle 1.4.0

And indeed, behaviour is the same as @sevarozh described above (It looks like the "Leaflet" library is loaded later than L.Icon.Default.imagePath is called in startup.js)

**Comment by fashxp** [comment]
can you share more detailed steps to reproduce? 
can it be reproduced on our demo?

**Comment by robertSt7** [comment]
@mhgtlc @sevarozh @aarongerig @storbahn Could you please test if this patch fix the problem? TIA 
https://github.com/pimcore/admin-ui-classic-bundle/pull/697

**Comment by aarongerig** [comment]
@robertSt7 This indeed resolves the issue on my side. 👍🏻
