### ISSUE TITLE
Handle pimcore.helpers.download exceptions

### ISSUE THREAD

**Issue by dvesh3** [pimcore/admin-ui-classic-bundle#126]
At the moment, exceptions are thrown e.g. `createNotFoundException` and not handled in js.

this one tricky to reproduce with default scenarios so it needs a bit of a tweaking:
 - tweak a controller action (for downloading) to return `createNotFoundException` e.g. AssetController::downloadAction
 - Open asset image and click download.
 - the request will be redirected to 404 page instead of handling it gracefully in admin UI.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/148
