### ISSUE TITLE
[Improvement] [Codeception] Update database version on the lowest dependency. 

### ISSUE THREAD

**Issue by martineiber** [pimcore/admin-ui-classic-bundle#127]
Update the database version to the lowest dependency. Currently we run the tests with the lowest dependency against `mariadb:10.7`, but it should run against `mariadb:10.3` as the minimum requirement for Maria DB is 10.3.  => https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/System_Requirements#database-server

**Comment by dvesh3** [comment]
Fixed by #159
