### ISSUE TITLE
Update default login background screen

### ISSUE THREAD

**Issue by fashxp** [pimcore/admin-ui-classic-bundle#142]
... with following image

![2023-06_Backend_Background_Pimcore_11_Update](https://github.com/pimcore/admin-ui-classic-bundle/assets/8792145/c429bfd2-49eb-4667-a41a-d43e9496c86f)

**Comment by torqdev** [comment]
@fashxp Noticed the file size is much larger in size(1.25mb vs the old 82.8kb) and a .png instead of .svg. Would that be fine? Or would you be able to provide an .svg of the file?

**Comment by fashxp** [comment]
Good point, we need to use a svg

**Comment by fashxp** [comment]
![2023-06_Demo_Background_Pimcore_11_Update 1 (1)](https://github.com/pimcore/admin-ui-classic-bundle/assets/8792145/28650f7d-722e-4435-884b-fb08d620428f)

@robertSt7 here we go
