### ISSUE TITLE
[Bug] 500 error when opening grid

### ISSUE THREAD

**Issue by eraush** [pimcore/admin-ui-classic-bundle#149]
**Steps to reproduce:**

1. Login as admin user
2. Navigate to Data objects > Product data > Cars (or any other grid)

**Actual Result:** 
Internal server error is shown

**Expected result:**
No errors are displayed when opening grid
![get column config](https://github.com/pimcore/admin-ui-classic-bundle/assets/131660776/b95b4ffd-e43e-4c4b-9b8f-e81aa5968505)

**Comment by blankse** [comment]
@eraush I created a PR: https://github.com/pimcore/admin-ui-classic-bundle/pull/150

**Comment by aryaantony92** [comment]
Fixed by #150
