### ISSUE TITLE
[Bug] Opening empty folder in Assets caused UI broken

### ISSUE THREAD

**Issue by eraush** [pimcore/admin-ui-classic-bundle#156]
**Preconditions:**
1. User was logged in as admin on test env
2. Empty folder was created in Assets

**Steps to reproduce:**

1. Navigate to Assets
2. Click on empty folder

**Acrual result:**
1. UI is completely broken
2. User cannot open the tree
3. Endless loading
4. `TypeError: Cannot read properties of undefined (reading 'setActiveItem')`

**Expected result:**
User is able to open empty folder with no issues

**Additional info:** https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/public/js/pimcore/asset/folder.js#L81

![ui broken empty folder](https://github.com/pimcore/admin-ui-classic-bundle/assets/131660776/bb5e48ee-8e87-43dc-a172-23e180b88614)

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/158
