### ISSUE TITLE
[Bug] Error message dialog is broken

### ISSUE THREAD

**Issue by eraush** [pimcore/admin-ui-classic-bundle#157]
**Preconditions:**
1. User was logged in as admin on test env
2. Empty folder was created in Assets

**Steps to reproduce:**

1. Navigate to Assets
2. Click on empty folder
3. Click on any folder/expand tree

**Acrual result:**

1. Error message dialog is broken
2. User cannot close error dialog

**Expected result:**
Error dialog is displayed with close button

![error dialog 11](https://github.com/pimcore/admin-ui-classic-bundle/assets/131660776/c9d2cf59-48b4-4e88-9b9d-7127c2013e48)

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/158
