### ISSUE TITLE
[Task]: Add Upgrade Note about getDocumentTreeNodeConfig

### ISSUE THREAD

**Issue by kingjia90** [pimcore/admin-ui-classic-bundle#178]
UPDATE: It seems that doc is missing and should be described that it breaks when not changing

~Need a follow up of https://github.com/pimcore/admin-ui-classic-bundle/pull/129~

~These customization in bundles are not considered anymore~
https://github.com/pimcore/web-to-print-bundle/blob/4f46683fff81c6b88d537251a47d6da107a98720/src/Model/Document/Printcontainer.php#L45-L61
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/6014195/0cf3b8da-39eb-4957-9293-4d99636d53fe)

**Comment by dvesh3** [comment]
@kingjia90 what is the reason they are not considered anymore? AFAIK we kept the BC layer with https://github.com/pimcore/admin-ui-classic-bundle/pull/129/files#diff-2419e7874923e300cdf352f832999d7d1d85a77cb69e01b25b1bfa93bcf95c15R50

**Comment by kingjia90** [comment]
Likely is because of these changes 
https://github.com/pimcore/admin-ui-classic-bundle/pull/129/files?w=1#diff-c8d2b20afd88c82d036fe3758fa9eaf1fc8b93237abf1e932cbf4519ff345a89R216

**Comment by kingjia90** [comment]
See also https://github.com/pimcore/headless-documents/issues/158 that is related for headless document

**Comment by aryaantony92** [comment]
This is obselete now as https://github.com/pimcore/admin-ui-classic-bundle/pull/205 gets merged and also the refactored methods were internal.
