### ISSUE TITLE
Add CSP Headers for open street maps

### ISSUE THREAD

**Issue by aashan10** [pimcore/admin-ui-classic-bundle#188]
I have a dataobject with a geopoint field.
After Pimcore 11 Update, whenever I try to add a point from openstreet maps, it shows me this error:

![Screenshot 2023-07-31 at 16 17 41](https://github.com/pimcore/admin-ui-classic-bundle/assets/18713900/730eb65a-eac3-4ee6-9ed9-1af89be61a17)
and on the console I see this:

![Screenshot 2023-07-31 at 16 23 17](https://github.com/pimcore/admin-ui-classic-bundle/assets/18713900/874640fe-c386-4e72-85ab-d3e6fa9b73ae)

It seems like a csp header is missing for open street maps

**Comment by aryaantony92** [comment]
Could be related https://github.com/pimcore/pimcore/issues/15661

**Comment by kingjia90** [comment]
Thank you @aashan10 !
Can you please check again if https://github.com/pimcore/admin-ui-classic-bundle/pull/210  resolves the issue?

**Comment by kingjia90** [comment]
Fixed by #210
