### ISSUE TITLE
Incorrect loading of translations for username and password on login screen

### ISSUE THREAD

**Issue by limenet** [pimcore/admin-ui-classic-bundle#202]
On the login screen, there's a slight difference between the placeholders for `username` and `password`:

<img width="317" alt="image" src="https://github.com/pimcore/admin-ui-classic-bundle/assets/474329/7bb6eeff-ee45-4201-9f92-a23e696debb8">

While this isn't much of an issue in English, in German it shows up as "username" and "Passwort".

There's an admin translation for the key `password` (and also for `Password`...) in `translations/admin.en.yaml` however there's none for `username`; that one only exists in `translations/admin_ext.en.yaml`.

What's the correct fix here, to load/merge translations from `admin_ext.*.*yaml` or to duplicate the relevant key from `admin_ext.*.yaml` to `admin.*.yaml`?

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/341

**Comment by kingjia90** [comment]
We moved the translation from `admin_ext` to `admin` 
https://github.com/pimcore/admin-ui-classic-bundle/pull/349

Thank you again for reporting!
