### ISSUE TITLE
[Bug] Event pimcore.events.prepareAffectedNodes details not correctly built after renaming assets or data objects

### ISSUE THREAD

**Issue by mattamon** [pimcore/admin-ui-classic-bundle#203]
### Version

1.0 - 1.x

### Steps to reproduce

Pretty hard to without a custom tree, but should be available with an internal feature

### Actual Behavior

After renaming an asset or an data object in the custom tree, the renamed element is marked as dirty even though it is updated in the standard tree correctly

![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/38959016/4db0bbc8-2157-4ed6-9c3c-f486cdc03d3e)

Another Problem is, if you try to rename the element again, the old value will show up

### Expected Behavior

Event pimcore.events.prepareAffectedNodes is built correctly and the field is not marked as dirty anymore and updated accordingly as it works for the documents.

**Comment by mattamon** [comment]
@robertSt7 this problem still persists. Now even renaming documents does not work anymore. 
If you rename something it gets flagged as dirty.

Please try to reproduce it with backend power tools bundle and the bookmark list.

**Comment by robertSt7** [comment]
@mattamon Please use the [post edit events](https://github.com/pimcore/admin-ui-classic-bundle/pull/307) and add a line like this `pimcore.helpers.updateTreeElementStyle('bookmarklist_1', ``${id}-object-root``, rdata.treeData);` to it for fixing the renaming issue
