### ISSUE TITLE
Forgotten password cannot be reset

### ISSUE THREAD

**Issue by epochlabs-dev** [pimcore/admin-ui-classic-bundle#215]
The "forgot your password" process does not allow a user to reset a forgotten password.

The temporary login link gives the user access to the system, but when attempting to change their password, the system gives the error "Given password is incorrect". This occurs whether the "Old password" field is filled out or left blank.

Pimcore\Bundle\AdminBundle\Controller\Admin\UserController::updateCurrentUserAction() is checking for the parameter "password_reset" in the admin session, but it appears this parameter is not being set anywhere. In Pimcore 10 this was handled by Pimcore\Bundle\AdminBundle\Security\Guard\AdminAuthenticator::getUser(), however it does not seem to have been carried across to the Pimcore 11 code.

**Comment by dvesh3** [comment]
Fixed by #216
