### ISSUE TITLE
[Bug] Uncaught TypeError: Cannot read properties of undefined (reading 'items') after changing perspective (e.g. catalog)

### ISSUE THREAD

**Issue by eraush** [pimcore/admin-ui-classic-bundle#229]
**Steps to reproduce:**

1. Login as admin user
2. Click File > Perspectives > Catalog

**Actual Result:** 
`Uncaught TypeError: Cannot read properties of undefined (reading 'items')`

**Expected result:**

No errors were thrown
![catalog perspective](https://github.com/pimcore/admin-ui-classic-bundle/assets/131660776/00e87b48-5239-434a-8083-65acfaecc245)

**Comment by dvesh3** [comment]
Related to enterprise bundles and fixed there.
