### ISSUE TITLE
Transformed value of special characters in the translations are displayed in the templates

### ISSUE THREAD

**Issue by aryaantony92** [pimcore/admin-ui-classic-bundle#234]
Please see https://github.com/pimcore/pimcore/discussions/15345#discussioncomment-6690814

**Comment by aryaantony92** [comment]
Related to https://github.com/pimcore/admin-ui-classic-bundle/issues/182

**Comment by cadeyrn** [comment]
@aryaantony92: https://github.com/pimcore/pimcore/discussions/15345#discussioncomment-6690814 links to https://github.com/pimcore/pimcore/issues/15740 and that issue closed as fixed, as well as #182. Can this issue be fixed now?

To quote myself from https://github.com/pimcore/pimcore/issues/15827 for the rationale why I think it's important to fix:

> Otherwise I would be forced to use the |raw filter for all translations in all templates as in every translation the „and“ symbol could potentially be used. That would reduce the security level of the application.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15960

**Comment by Cruiser13** [comment]
Actually this does not seem to be fixed @kingjia90 .
Tested on pimcore 11.1.5 and admin-ui-classic-bundle 1.3.4.

Sample Code:

```twig
{% set headline = pimcore_input('headline') %}
{% if editmode %}
{{ headline|raw }}
{% else %}
{{ headline }}
{% endif %}
```

Put the following text in Backend:
Marketing & Entwicklung

Will appear as Marketing &amp; Entwicklung in frontend (non editmode)

**Comment by kingjia90** [comment]
Thank you for your report!

I think it got reverted something on

https://github.com/pimcore/pimcore/commit/c5eb0a3a4f1c3b156da42bb821f9c52adc9932d6

Therefore you might be right that something may not be actually fixed as what i recall.

Could you please open a brand new issue with your described case? Will take a look then

**Comment by Cruiser13** [comment]
@kingjia90 done, thanks!
