### ISSUE TITLE
tabs for documents / objects / assets are almost impossible to read on :hover 

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/admin-ui-classic-bundle#243]
STR:

1. open a document, object or asset
2. move the cursor on one of the tabs (for example „Navigation & Properties“ in a document

Actual:

White font on light grey background, bad readability.

![Bildschirmfoto 2023-08-28 um 14 14 52](https://github.com/pimcore/admin-ui-classic-bundle/assets/1100614/f0ceb001-83de-43e0-827e-d136a0373dda)

Expected:

Much better color contrast, better readability.

Tested in Firefox and Chrome, also reproduced on demo.pimcore.fun.

**Comment by cadeyrn** [comment]
This should probably be classified as a bug rather than an improvement, as it's clearly wrong and a regression. 😉

**Comment by blankse** [comment]
@cadeyrn Is already fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/261

**Comment by jdreesen** [comment]
Should already be fixed (but not yet released) by #261.

**Comment by cadeyrn** [comment]
Thank you for fixing and referencing the PR! I will close the ticket accordingly. 😊

**Comment by Fabian-Hofer-Mastertent** [comment]
Can we reopen this issue? (or should i make a new issue?) 
The problem is solved in the document view but not in the print view

![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/99820683/4bccd920-f388-4183-a46f-95b1fb8b1a19)
(Screenshot from the current pimcore demo admin)
