### ISSUE TITLE
[Bug] ClassificationController $sorter initialization

### ISSUE THREAD

**Issue by dbarattini-jkl** [pimcore/admin-ui-classic-bundle#254]
Pimcore v11.0.8
When accessing the ClassificationStore panel from the Classification Store settings an exception is thrown:
Message: Typed property Pimcore\Model\DataObject\Classificationstore\KeyGroupRelation::$sorter must not be accessed before initialization

Settings > Classification Store > Select classification store > Groups > Double click on group to edit keys.
Every popup for classification store management (inside views, schema definitions for datahub ecc) is throwing the same exception.

<img width="924" alt="image" src="https://github.com/pimcore/admin-ui-classic-bundle/assets/114909034/3a8d323a-5953-45c8-bfe8-b23de2581ee1">

**Comment by dbarattini-jkl** [comment]
Pls, check the bug asap, is blocking the Classification Store usage inside Pimcore Platform

**Comment by dvesh3** [comment]
Hi @dariobarattini-hes It works on [demo](https://demo.pimcore.com/admin/) (creds: superuser/enterprisedemo). Are the steps to reproduce correct?

**Comment by dbarattini-jkl** [comment]
Hi, yes, here is the list of the bundles installed:

<img width="766" alt="image" src="https://github.com/pimcore/admin-ui-classic-bundle/assets/114909034/4869d2b6-d74e-4112-9cb2-348fa5b01ac4">

Many of the classification stores are input quantity value fields, don't know if this could be the problem.
Pimcore v11.0.8, admin-ui-classic-bundle v1.1.1

**Comment by dbarattini-jkl** [comment]
@dvesh3 any news about? Still having the issue

**Comment by dbarattini-jkl** [comment]
Closed, bug concerning the creation of classification stores using php api without setting the sorter int.
