### ISSUE TITLE
Event pimcore.events.initializeWysiwyg not called for documents

### ISSUE THREAD

**Issue by mhgtlc** [pimcore/admin-ui-classic-bundle#294]
It seems listener for `pimcore.events.initializeWysiwyg` does not work for `documents`, it works for object,  but it is not called on documents
```
document.addEventListener(pimcore.events.initializeWysiwyg, function(ev){
        console.log(ev);
});
```

Also (may be this is related)
```
console.log(pimcore.object.tags.wysiwyg);
```
outputs:
```
ƒ klass() {
       this.initialize.apply(this, arguments);
}
```        

In this case:
```
console.log(pimcore.document.editables.wysiwyg);
```
Receive error:
```
Cannot read properties of undefined (reading 'wysiwyg')
```

Even if i do:

```
var myConfig = { .... };
pimcore.document.editables = pimcore.document.editables || {};
pimcore.document.editables.wysiwyg = pimcore.document.editables.wysiwyg || {};
pimcore.document.editables.wysiwyg.defaultEditorConfig = myConfig;
```
at a later stage `pimcore.document.editables.wysiwyg.defaultEditorConfig` is empty
can you please check it?

**Comment by mhgtlc** [comment]
Found a possible reason.
`pimcore/object/tags/wysiwyg.js` is included from very beginning:
https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/templates/admin/index/index.html.twig#L526
but `pimcore/document/editables/wysiwyg.js` at a later stage.

**Comment by fracsi** [comment]
Document in editmode is loaded in an iframe.
If you want to add custom JS for every document in editmode, you can add that js in the document's layout template.
E.g.:
```twig
{%- if editmode -%}
  <script src="/path-to-your-script.js"></script>
  {# or #}
  <script>
    var myConfig = { .... };
    pimcore.document.editables = pimcore.document.editables || {};
    pimcore.document.editables.wysiwyg = pimcore.document.editables.wysiwyg || {};
    pimcore.document.editables.wysiwyg.defaultEditorConfig = myConfig;
  </script>
{%- endif -%}
```

OR

You can subscribe to `Pimcore\Event\BundleManagerEvents::EDITMODE_JS_PATHS` (`pimcore.bundle_manager.paths.editmode_js`) event and add your custom js path.
See: [Loading Assets in the Admin UI](https://pimcore.com/docs/platform/Pimcore/Extending_Pimcore/Bundle_Developers_Guide/Loading_Admin_UI_Assets#event-based)

**Comment by mhgtlc** [comment]
@fracsi got it, thank you very much!
