### ISSUE TITLE
[Bug]: WYSIWYG Editable is not empty when no content is added

### ISSUE THREAD

**Issue by GALPR** [pimcore/admin-ui-classic-bundle#304]
After adding some content to a WYSIWYG editable and removing it again it is not cleared correctly. The persisted value is `<p><br /></p>` but it should be empty. This seems to be the same issue as https://github.com/pimcore/admin-ui-classic-bundle/issues/182 just at a different place.

**Comment by GALPR** [comment]
@robertSt7 I noticed that this also affects DataObject WYSIWYG editables, When such a WYSIWYG is marked as mandatory, an empty one still counts as valid. `<p><br data-mce-bogus="1"></p>` is added to the database in this case

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/311

**Comment by GALPR** [comment]
Thanks!
