### ISSUE TITLE
Mime Type is not updated on replaceAssetAction

### ISSUE THREAD

**Issue by patrick-rudolph-umusic** [pimcore/admin-ui-classic-bundle#338]
https://github.com/pimcore/admin-ui-classic-bundle/blob/a4f807ed2f05653524e298485325df9c102dc200/src/Controller/Admin/Asset/AssetController.php#L601

When uploading a new version of an asset, the mime type never gets updated

**Comment by kingjia90** [comment]
Works fine on my end, any more details on how to reproduce it?
Could you please also try to double-check that the file you are uploading is the right (a different one) MIME in a third party service, just to be sure it's not simply with the wrong file extension?

**Comment by patrick-rudolph-umusic** [comment]
@kingjia90 
Upload a jpg. 
Check mime type in embedded metadata. 
Upload a new version for this asset. This time upload a png.
Refresh the asset and check mime type in embedded metadata again. It still says "image/jpg"

**Comment by kingjia90** [comment]
ahh, got it, it's related to the `embedded meta info` as a whole, not even strictly to Mime type. 
Confirming the issue
