### ISSUE TITLE
Default data in pimcore_table are not applied

### ISSUE THREAD

**Issue by fuw-nielsjensen** [pimcore/admin-ui-classic-bundle#353]
### Pimcore version:
11.1.1

### Steps to reproduce:
Create a Table Editable:
```twig
{{ pimcore_table("productProperties", {
    "width": 700,
    "height": 400,
    "defaults": {
        "cols": 2,
        "rows": 3,
        "data": [
            ["Attribute name", "Value"],
            ["Color", "Black"],
            ["Size", "Large"],
            ["Availability", "Out of stock"]
            ]
        }
    })
}}
```

### Actual Behavior:
The default data are not taken into account.

### Possible solution:

The initialize method of pimcore.document.editables.table checks if data is not set to apply the default data:

https://github.com/pimcore/admin-ui-classic-bundle/blob/3c7f80d32129837d42a8b198a1e0de5daa210f79/public/js/pimcore/document/editables/table.js#L23

But this check fails, because data is an empty array. Changing ```if (!data) {``` to ```if (!data || data.length === 0) {``` would fix this issue in my case.

**Comment by kingjia90** [comment]
Thank you for reporting and the PR!

Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/371
