### ISSUE TITLE
[Bug] Key bindings show spacebar as empty string 

### ISSUE THREAD

**Issue by mattamon** [pimcore/admin-ui-classic-bundle#358]
Adding a keybinding with the spacebar will result in the following UI Problem:

![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/38959016/017b4875-cfa7-4208-be53-cd2dfa8e95df)

For a better user experience we should should change it to "Space" like we do it for Shift, Ctrl and Alt

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/357
