### ISSUE TITLE
Tree shows Root for all names

### ISSUE THREAD

**Issue by matthiashamacher** [pimcore/admin-ui-classic-bundle#363]
# Versions
Pimcore: 11.1.2
Admin UI Classic Bundle: 1.2.2

# Problem
After we updated to the latest versions all the file, folder, asset, object, document Names in the trees where replace by the word "Root". This only is a problem of the tree not of the assets etc themself. If you click on one the tab name and also the names in the grid of a folder are all correct

![CleanShot 2023-11-28 at 14 33 02](https://github.com/pimcore/admin-ui-classic-bundle/assets/32356549/c4e9086b-a94f-41f0-b037-be4c5cbb6112)

# Debugging Information
We had a look into the problem and it seems to be the problem of the admin style change of #267 From what we can see we always get null as result of `$adminStyle->getElementText()` Therefore the previous value is overridden with null which results to a fallback of ExtJS to show "Root". The weird thing is that we have another project with the same versions where the error does not occur. I've checked, we don't have any custom admin styles, so that cannot be the problem in this case.
Any Ideas what else we can check or what the problem could be?

**Comment by matthiashamacher** [comment]
Our current workaround is to check if `$adminStyle->getElementText()` is null and only if that is not the case we set it to the array.

**Comment by hbauer** [comment]
@kingjia90 This is still a problem with the newest release. @matthiashamacher proposed a solution that solves the problem.

**Tested it with:**
Pimcore: 11.1.4
Admin UI Classic Bundle: 1.3.1

**Comment by kingjia90** [comment]
Thank you for suggesting and testing the fix

Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/399
