### ISSUE TITLE
Grid "direct_sql_query" was removed from 10 to 11 - why?

### ISSUE THREAD

**Issue by tecbird** [pimcore/admin-ui-classic-bundle#374]
We updated our pimcore vom v10 to v11 and direct sql icon / field was removed.
What's the reason for this?

https://github.com/pimcore/pimcore/blob/10.6/bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
=> createSqlEditor and other stuff

File here in classic ui:
https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/public/js/pimcore/object/helpers/gridTabAbstract.js

The diff between those files is exact the removel of the sql function...

**Comment by fashxp** [comment]
We needed to remove that due to security reasons, as security auditors regularly classified that as potential sql injection.
See also https://github.com/pimcore/pimcore/issues/13224.

**Comment by kingjia90** [comment]
More specifically https://github.com/pimcore/pimcore/pull/13131#issuecomment-1256132467

**Comment by tecbird** [comment]
thanks for your information!
