### ISSUE TITLE
Error resending mails

### ISSUE THREAD

**Issue by valentin-** [pimcore/admin-ui-classic-bundle#381]
Trying to resend/forward mails in "Sent Emails" results in an error.

![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/90033/9e330b88-6470-4300-a9af-c8498499d1a4)

https://github.com/pimcore/admin-ui-classic-bundle/blob/1eeb2536ebb3f8e7f596743ef9a214f582d8cd4a/src/Controller/Admin/EmailController.php#L529

In my case $data is a string, not an array and could also be an object (if an objectId is given).

**Comment by ghost** [comment]
@valentin- Thanks for reporting this issue. I tried to reproduce it, but got no error on my installation. So could you please provide us with some more details (without personal or confidential information, of course)? So e.g. your parameters (strings, objects), your setup, error messages etc.? Thanks a lot in advance!

**Comment by valentin-** [comment]
@wisconaut did you try to resend a sent mail having a document with parameters?

I got a mail document for forgot password. Using "Send Test-Email" in the mail document view the mail sends fine setting following parameters:

Username: {{ email }}
This is the link: {{ link }}

Trying to resend/forward this email in "Sent Emails" fails.

```
Message: Pimcore\Bundle\AdminBundle\Controller\Admin\EmailController::parseLoggingParamObject(): Return value must be of type ?array, string returned
Trace: 
in /app/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/EmailController.php:546
#0 /app/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/EmailController.php(358): Pimcore\Bundle\AdminBundle\Controller\Admin\EmailController->parseLoggingParamObject(Array)
#1 /app/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\AdminBundle\Controller\Admin\EmailController->resendEmailAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /app/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /app/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /app/public/index.php(42): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main}

```

**Comment by kingjia90** [comment]
Looks like the return type was wrong in the phppdoc and during Pimcore 11 native return type refactoring

https://github.com/pimcore/admin-ui-classic-bundle/blob/fed32936245ab3bd1baa9ac788a096baa6bf8681/src/Controller/Admin/EmailController.php#L529-L547

The return type should be `mixed`, `$data` could be a string or even a object, when not an array
