### ISSUE TITLE
[Bug]:  Removed if-statement condition inside DocumentControllerBase Interface 

### ISSUE THREAD

**Issue by HermanoGrimmo** [pimcore/admin-ui-classic-bundle#398]
Pimcore version 
11

When updating from Pimcore 10 to 11, an If-statement condition has been removed in the DocumentControllerBase:

Pimcore 10 version:
![admin-bundle-10](https://github.com/pimcore/admin-ui-classic-bundle/assets/64836794/8c5602f3-62b1-4e27-8c17-e85cde9fb516)

Pimcore 11 version:
![admin-bundle](https://github.com/pimcore/admin-ui-classic-bundle/assets/64836794/62aa1fe9-209b-4e8e-90e3-ddcf18532905)

This results in my local project entering the If branch when it shouldn't. Is there a reason why the condition was removed, and if not, is it possible to add it back? This behavior was not reproducable with the Pimcore Demo.

**Comment by kingjia90** [comment]
Thank you, it seems that it was an unintentional removal
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/427
