### ISSUE TITLE
[Bug] JS Errors on Bricks with many-to-many relation and specific configuration

### ISSUE THREAD

**Issue by aKugler** [pimcore/admin-ui-classic-bundle#406]
Hi!

A user creates a new brick in the Admin UI. It contains a FieldContainer and a Fieldset. The fieldset contains an (advanced) many-to-many relation. 
[objectbrick_Test_export.json](https://github.com/pimcore/admin-ui-classic-bundle/files/14062696/objectbrick_Test_export.json)
 You can then also add corresponding objects in the relation. 

<img width="1060" alt="Bildschirmfoto 2024-01-26 um 09 34 33" src="https://github.com/pimcore/admin-ui-classic-bundle/assets/6008333/539ec2c2-9a48-4c28-89b0-6a4cc750a054">

User 2 then has the idea of dragging and dropping the fieldset into the FieldContainer. At that moment, the bricks are no longer displayed, but the browser console is full of JS errors.
<img width="277" alt="Bildschirmfoto 2024-01-26 um 09 34 57" src="https://github.com/pimcore/admin-ui-classic-bundle/assets/6008333/afd76ce7-62b1-44d2-9de4-3a239fa1b0f0">
<img width="569" alt="Bildschirmfoto 2024-01-26 um 09 35 19" src="https://github.com/pimcore/admin-ui-classic-bundle/assets/6008333/ad107ea5-4fac-402f-8b36-0586f78ecdc1">
[objectbrick_Test_export-3.json](https://github.com/pimcore/admin-ui-classic-bundle/files/14062706/objectbrick_Test_export-3.json)

Pimcore 11.1.4 
Admin UI 1.3.1

Best regards
Andreas

**Comment by robertSt7** [comment]
Hi @aKugler thanks for reporting this bug. The problem here is that it shouldn't be possible to put a `fieldset` into a `field container`. I will provide a fix for the drag and drop validation

**Comment by aKugler** [comment]
Hi @robertSt7 !
Thank you very much, that sounds good. It's just important to me that no one else stumbles across it. I wouldn't have expected these effects. Probably also because I was working on import and data enrichment and didn't build the data model.

**Comment by robertSt7** [comment]
fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/462
