### ISSUE TITLE
Update pimcore/pimcore dependency to ^11.2

### ISSUE THREAD

**Issue by fashxp** [pimcore/admin-ui-classic-bundle#408]
as followup of https://github.com/pimcore/admin-ui-classic-bundle/pull/386

**Comment by kingjia90** [comment]
Indirectly resolved by https://github.com/pimcore/admin-ui-classic-bundle/pull/423/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R14
