### ISSUE TITLE
[Bug] Broken grid display of dynamic select options

### ISSUE THREAD

**Issue by patrick-rudolph-umusic** [pimcore/admin-ui-classic-bundle#409]
https://github.com/pimcore/admin-ui-classic-bundle/blob/9258d42920dbb475badc1adea59a7552ab089ac4/public/js/pimcore/object/tags/select.js#L102

Method "getGridColumnConfigDynamic" is never called because if statement is wrong.

<img width="126" alt="Bildschirmfoto 2024-01-31 um 12 02 56" src="https://github.com/pimcore/admin-ui-classic-bundle/assets/59048687/05a481db-f41d-420e-8335-b0fd16234160">

**Comment by jdreesen** [comment]
Looks more like a broken link than a smart one xD

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/426
