### ISSUE TITLE
How to get areabricks

### ISSUE THREAD

**Issue by dokselblackbit** [pimcore/admin-ui-classic-bundle#424]
Hello everyone. 
I created a bundle. How can I get all areabricks (editables) from current page? 
I created customer view (Content) and added some tree (Drag&Drop Tree) which includes areabricks. When I click on some items (text (wysiwyg)) in the left sidebar I can change styles current areabrick in content, but can't give it el.onfocuse(). How can I do it?
<img width="1680" alt="Screenshot 2024-02-15 at 15 59 11" src="https://github.com/pimcore/admin-ui-classic-bundle/assets/116077841/83c76fe3-cf48-4545-9d98-2c0761b27795">

**Comment by kingjia90** [comment]
Thank you but sounds like the wrong place to ask 😄 please post this again in the [discussion area](https://github.com/orgs/pimcore/discussions) 
but i didn't get it tough, please also rephrase a little bit. If there's a problem with `onfocus`, i'd recommed to keep an eye to the js console in web developer tools, maybe something is broken
