### ISSUE TITLE
[Improvement, EC]: Display read-only asset metadata when granted view permission

### ISSUE THREAD

**Issue by ghost** [pimcore/admin-ui-classic-bundle#435]
### Pimcore version

11.x

### Actual Behavior

In the backoffice, the asset metadata tab disappears when either the workflow state disallows editing (modify, save, publish, unpublish, delete, rename false) or a user is lacking publish rights, so the meta data can not be read.
The metadata is only visible when it is editable.

### Expected Behavior

The metadata should be visible by correct rights.

**Comment by kingjia90** [comment]
Moving to admin-ui-classic-bundle, seems fine but could provide a read-only for `view` permissions
https://github.com/pimcore/admin-ui-classic-bundle/blob/7cf5e121ee103661697fb2ea23e12ee6f3ea14f1/public/js/pimcore/asset/image.js#L76-L78

See also https://pimcore.atlassian.net/browse/PEES-243?focusedCommentId=20220
