### ISSUE TITLE
There is no way to filter objects in grid views based on whether they are of variant type or not

### ISSUE THREAD

**Issue by lucfumagalli** [pimcore/admin-ui-classic-bundle#464]
I have already posted this issue in "**pimcore/pimcore**" repo. I report in this repo just to have a link to the [issue: #16681](https://github.com/pimcore/pimcore/issues/16681).

### The issue:
**Steps to reproduce**
Select a folder. Now in the grid view you can see objects and variants together.

**Actual Behavior**
In the grid views, all objects in a given folder are retrieved, including variants.
Having removed in Pimcore 11 the ability to do a direct query, I am no longer able to get only the objects or only the variant objects.

**Expected Behavior**
It would help me greatly to have a way to choose which objects to show in the grid view, based on whether they are normal objects, variants, or perhaps both.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/465
