### ISSUE TITLE
Id and class title is missing in object toolbar submenu

### ISSUE THREAD

**Issue by mhgtlc** [pimcore/admin-ui-classic-bundle#481]
No id and type is displayed in object toolbar submenu. Investigated it and found that it was removed here:

https://github.com/pimcore/admin-ui-classic-bundle/commit/686e913#diff-19561231ee9a8f94a4e06afe4d726dd9f4be310a6ab04e3ed22d9289e9f1fc45L574

Is that on purpose? Is there an option to put it back?

**Comment by blankse** [comment]
I want it also back.

@kingjia90 Was that an accident?

**Comment by kingjia90** [comment]
It got moved there to declutter the bar, iirc
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/6014195/37098d50-4933-44e4-bf3f-7dd1364126a2)
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/6014195/5f0a809a-bf2f-4396-b4fc-79571aa12c69)

**Comment by kingjia90** [comment]
Closing for the moment as it seem intended.

Please re-open as an improvement request or even better by providing a PR for event listeners to inject/alter the toolbar layout if it's still desiderabile to have it back in its former position or so.

**Comment by MarkTro** [comment]
I want it back, too! It was always very helpful to see the ID if you have similar objects tab open. 

And by the way it would be even more helpful if you could see the tree path in breadcrumb style, especially if you have similar documents at different document tree positions.

**Comment by kingjia90** [comment]
Thank you for your feedback and input!
I'll bring this to the attention of the Team

**Comment by kingjia90** [comment]
It wasn't intended, more specifically, that change was only for the [Light Theme](https://pimcore.com/docs/platform/Light_Theme_Admin_UI/), in which is more crowded in the (assets) toolbar but here in the classic one there is plenty of space and there are no reasons to remove it.

I've opened a PR #516 that reverts all that changes (not just objects), my apologies for not giving it the adequate weight and dig more the first time, (so so sorry that i couldn't even wait for monday to work on it) and Thank you all again for bringing this topic up

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/admin-ui-classic-bundle/pull/516
