### ISSUE TITLE
[Bug]: Upload Dialog remains visible on failure. 

### ISSUE THREAD

**Issue by martineiber** [pimcore/admin-ui-classic-bundle#497]
When using the `pimcore.helpers.uploadDialog()` https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/public/js/pimcore/helpers.js#L1019

In case of an error from the Backend, the upload Dialog says and can not be removed. 

The console shows following error: 
`Uncaught ReferenceError: pbar is not defined`

![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/11687066/61b140ce-b019-4e79-9313-2da68fd308a0)

**Comment by blankse** [comment]
@martineiber I created a PR: https://github.com/pimcore/admin-ui-classic-bundle/pull/501
Can you test it?

**Comment by martineiber** [comment]
Thank you for the fix :)

Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/501
