### ISSUE TITLE
Cleanup / move files from other bundles

### ISSUE THREAD

**Issue by brusch** [pimcore/admin-ui-classic-bundle#5]
- [x] https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/public/css/print/print-printermarks.css
- [x] https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/public/css/adminer-modifications.css
- [x] https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/public/css/word-export.css
- [x] https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/public/css/reports.css

**Comment by aryaantony92** [comment]
Removed reports.css and adminer-modifications.js as the were not used anywhere
