### ISSUE TITLE
[Bug]: clearing cache creates Status: 500 | Internal Server Error

### ISSUE THREAD

**Issue by varshaekrocx** [pimcore/admin-ui-classic-bundle#528]
### Pimcore version

11

### Steps to reproduce

1. Clear the cache from admin
![image](https://github.com/pimcore/pimcore/assets/124252930/3e831f5b-8fbc-4397-b726-dc9425142ce1)

2. Or use pimcore cache command
php bin/console pimcore:cache:clear

### Actual Behavior

On loading pimcore admin it is showing Internal server error
![image](https://github.com/pimcore/pimcore/assets/124252930/a62e075b-b022-45b4-aca2-2cc7853e1f15)
![image](https://github.com/pimcore/pimcore/assets/124252930/954ec154-f82d-4606-9835-7e6d968b24f8)

### Expected Behavior

Admin should work fine.
![image](https://github.com/pimcore/pimcore/assets/124252930/75cdd0a2-44f0-454b-ae92-37697d3ce488)

**Comment by kingjia90** [comment]
Thank you for reporting!
I've opened a PR https://github.com/pimcore/admin-ui-classic-bundle/pull/529 that may fix this error, however, there might be some other problems underneath, 🤔 let me know if there's any other following error

**Comment by varshaekrocx** [comment]
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/124252930/70af02f3-2e36-41cd-be31-0431c8344f6c)
if i add these two entries using sql then my project is working but cache warming is not able to generate these automatically

when i perform the cache warming command i get this
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/124252930/c0b8b1e3-cdfd-4cc8-8e4e-6fc2b15bc258)

**Comment by varshaekrocx** [comment]
how can i resolve this. Because cache warmingup is not working as expected.

**Comment by kingjia90** [comment]
As suspected/foreseen, there might be some problems underneath and those reported not found elements might need some manual intervention. 
Specifically, I don't know what should be done (i will consult a colleague and let you know), but would suggest to check how these elements were deleted and which one are referring/depending/related to these that may need a clean up, if are some kind of "leftovers".
