### ISSUE TITLE
[Bug, EC]: Visual mandatory flag on Classification Store group when attribute is not mandatory

### ISSUE THREAD

**Issue by ghost** [pimcore/admin-ui-classic-bundle#575]
The issue occurs when an attribute exists twice on an object from a classification store (i.e. it is part of two or more separate groups assigned to the data object) and it is marked as mandatory in only one, it will mark (red asterisk) the non mandatory attribute(s) as mandatory as well. This issue is only display / visual and does not impact functionality.

Investigation showed this is how classification store details are loaded: field definitions are cached to limit how many times data is loaded from the db. 

![image1](https://github.com/pimcore/admin-ui-classic-bundle/assets/150000890/544476c2-b4cf-43c6-b2ad-0de629c0713d)
![image2](https://github.com/pimcore/admin-ui-classic-bundle/assets/150000890/6d185620-aee5-4fd6-9534-e34d338b84e3)
![image3](https://github.com/pimcore/admin-ui-classic-bundle/assets/150000890/ae83886d-4148-4b27-913f-4277e6bf219d)
![image4](https://github.com/pimcore/admin-ui-classic-bundle/assets/150000890/79968ff1-1292-404d-80fb-160fdf7ed9ce)

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/17680
