### ISSUE TITLE
Variant option should not be shown in the dropdown for filtering in the grid if no variants avaliable

### ISSUE THREAD

**Issue by heigpa** [pimcore/admin-ui-classic-bundle#577]
**Steps to reproduce**

- Login as admin
- Open a folder without variants in the grid
- Open the dropdown 'Type to show'

**Actual result**

- Option for 'just variant products' is shown

**Expected result**

- If no variant is available, the option should be hidden

**Comment by markus-moser** [comment]
The select box should be hidden when variants are not enabled in the class editor.
