### ISSUE TITLE
Timestamp for notification does not show client time

### ISSUE THREAD

**Issue by heigpa** [pimcore/admin-ui-classic-bundle#586]
**Steps to reproduce**
- Login as admin
- Send a test notification
- Open notifications and check date column

**Expected behaviour**
- Value of date column equals client time

**Actual behaviour**
- Value of date column is + 2 hours

**Environment**
- Platform Test System

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/554

More specifically by https://github.com/pimcore/admin-ui-classic-bundle/commit/6ae0a3bd0f0029dbce911c6acc18843c603b1c16#diff-7bf05bbe7e68b1a100fa9120c8b39324914cfcd67f088a774084239391e23644R97
