### ISSUE TITLE
[Bug] Route "pimcore_admin_element_getnicepath" does not support inheritance

### ISSUE THREAD

**Issue by skoch-twocream** [pimcore/admin-ui-classic-bundle#591]
The route "pimcore_admin_element_getnicepath" does not support inheritance. The columns are left empty:

![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/54348050/d6077599-40ba-4f13-b7d7-d24e155f8132)
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/54348050/cc1e55d4-9e77-4c6f-a4dc-de91903a4c1d)

After I adjust the code in file `src/Controller/Admin/ElementController.php` as follows:
```diff
        if ($request->request->getBoolean('loadEditModeData')) {
            $idProperty = $request->get('idProperty', 'id');
            $methodName = 'get' . ucfirst($fieldname);
            if ($ownerType == 'object' && method_exists($source, $methodName)) {
+                DataObject\Concrete::setGetInheritedValues(true);
                $data = $source->$methodName();
+                DataObject\Concrete::setGetInheritedValues(false);

                $editModeData = $fd->getDataForEditmode($data, $source);
                // Inherited values show as an empty array
                if (is_array($editModeData) && !empty($editModeData)) {
```

Or alternatively by adding `DataObject\Concrete::setGetInheritedValues(true);` to beginn of the method.

Then this works:
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/54348050/780f6271-d358-4667-b6bd-5c5ae03a6349)
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/54348050/31af9735-a75f-40bb-ae37-f71b8c273168)

---

However, I am a little confused about the expected pimcore behaviour and how I can best resolve this via PR.
This commit with the comment leaves me a bit puzzled: 
https://github.com/pimcore/admin-ui-classic-bundle/commit/1acb2dd9893bc3cca14e959dcf1aa8f99ac4ca09

What is mean with the comment `Inherited values show as an empty array`?
Should inherited data for the table be processed somewhere other than here?

**Comment by fashxp** [comment]
Not sure about that comment, but it is pretty old. Maybe it describes exactly the current behavior and just leaves the values empty? 

Anyhow, we should use [this](https://github.com/pimcore/pimcore/blob/37c1b55b22de79d452c977d68ecad4d82f6a043f/models/DataObject/Service.php#L1962) helper function....

**Comment by skoch-twocream** [comment]
Okay, then we will test this with the helper function with and without path formatter and send a PR. Thanks!

FYI @noahcommandeur-twocream
