### ISSUE TITLE
Bug document Save Buttons

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/admin-ui-classic-bundle#592]
When a document gets published it is not possible anymore to "save only" without publishing. this behaviour can be tested in the pimcore demo

![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/14984260/c98bbabd-8c6d-4109-a93c-b4c67080e007)

**Comment by AlternateIf** [comment]
do we have any updates on this? @wisconaut

**Comment by ghost** [comment]
@AlternateIf We are on it, please give us some more time...

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/622

Thank you for reporting
