### ISSUE TITLE
Create GitHub Action to build static assets (Webpack/Encore)

### ISSUE THREAD

**Issue by brusch** [pimcore/admin-ui-classic-bundle#6]
Currently updating and building the Webpack build files (located in `public/build`) is a manual process. 
The goal of this task should be, that this process is fully automated using GitHub Actions and runs on a regular basis to also update npm packages to the latest available versions. 

- [ ] Update dependencies defined in `package.json` 
- [ ] Check if there were any changes
- [ ] Build Webpack Encore artefacts and update them in Git repository (if there were any changes/updates) 
- [ ] Tiggers for this workflow: cron (daily at night), on push/PR when any related config is getting changed ( e.g. `package.json`  or `webpack.config.js`, `public/assets/*` ....) and manual trigger

**Comment by fashxp** [comment]
won't do anymore.
