### ISSUE TITLE
[BUG] Workflow toolbar status info no localization

### ISSUE THREAD

**Issue by Melsa-Huebel** [pimcore/admin-ui-classic-bundle#613]
### Pimcore version

11.2.x

### Steps to reproduce

1. Configure workflow places
2. Provide translations for places in admin messages
3. Switch language in user (between provides translations)

### Actual behaviour

The language seems to just follow the symfony default language setup.

### Expected behaviour

Pimcore should consider the configured user language to switch to the given translation.

### Possible solution approach

The issue appears in the following template: `pimcore/vendor/pimcore/pimcore/bundles/CoreBundle/templates/Workflow/statusinfo/toolbarStatusInfo.html.twig`
The translator interface is passed as view parameter to the template but seems not to have the right context.
So a possible solution can be to set the correct locale (or language corresponding to the logged in user) inside the event listener: `pimcore/vendor/pimcore/admin-ui-classic-bundle/src/EventListener/WorkflowManagementListener.php` were the method `getToolbarHtml` is returning the rendered template mentioned above.
In the event listener its possible to use injections so it might be possible to call the setLocal method on the TranslatorInterface or something like that with the correct context based locale.

**Comment by kingjia90** [comment]
Thank you for reporting

This should be fixed by https://github.com/pimcore/pimcore/pull/17252 (11.3.1), let us know if it works, if not, feel free to re-open this or in a new issue with further details
