### ISSUE TITLE
`Access-Control-Allow-Origin` in AssetController

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/admin-ui-classic-bundle#676]
https://github.com/pimcore/admin-ui-classic-bundle/blob/4dff99bd4ffe260e58e1e819a7d3e3daf6a32a24/src/Controller/Admin/Asset/AssetController.php#L1234-L1235

Is the above `, '*'` intentional? Shouldn't it be `=> '*'`?

**Comment by NiklasBr** [comment]
Have you been able to research if this code is as intended @fashxp?

**Comment by kingjia90** [comment]
By looking at 
https://github.com/pimcore/admin-ui-classic-bundle/commit/4feb4314ba719e2ea08bdd782e0f3b5b2d5ee2db#diff-8a94426359af1cadbcb7fdeb7af5731ce2ac295a758ed07a38d36db9d5d85ff9R1261-R1262, it doesn't look intended (also incorrect line break) and should be considered as a typo instead, ~could you please provide a PR for it so it would be credited to you?~(nevermind i was quicker 😄 )

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/689
