### ISSUE TITLE
[Bug] Prevent accidentical removal of whole folder instead of deleting selected assets / objects does not work

### ISSUE THREAD

**Issue by heigpa** [pimcore/admin-ui-classic-bundle#698]
Steps to reproduce:
Login as admin
Open the list view of a folder
Select one item
Click the delete button

Actual behaviour:
Folder gets deleted

Expected behaviour:
Only selected element gets deleted

Environment: platform test system

**Comment by kingjia90** [comment]
Update: interestingly, it works on the normal admin ui, but somehow it's broken on the light theme
