### ISSUE TITLE
[Bug] Filter for relation throws an error

### ISSUE THREAD

**Issue by patrick-rudolph-umusic** [pimcore/admin-ui-classic-bundle#720]
The relation filters seem to be broken since version 1.6.1.

When trying to filter for relation ExtJS is throwing an error

<img width="643" alt="Bildschirmfoto 2024-10-14 um 15 33 33" src="https://github.com/user-attachments/assets/10602bcb-1772-44f6-a063-afcf278cb39a">

**Comment by jlsdohmen** [comment]
Seems to be only related to the grid view for many-to-one relation fields

**Comment by blankse** [comment]
@patrick-rudolph-umusic @jlsdohmen I created a PR: https://github.com/pimcore/admin-ui-classic-bundle/pull/741

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/741
