### ISSUE TITLE
Manual Tree Sorting not working

### ISSUE THREAD

**Issue by solverat** [pimcore/admin-ui-classic-bundle#722]
After https://github.com/pimcore/admin-ui-classic-bundle/pull/656 (@BlackbitDevs), it's no longer possible to manually sort objects.

That's because `node.needsPaging = true` always defines a (wrongly) given pagination.

https://github.com/pimcore/admin-ui-classic-bundle/blob/c68397e4e4fa83d6179e1a04b75fc28f2747a4ac/public/js/pimcore/overrides.js#L403

**Comment by mattamon** [comment]
@solverat could you please check if #723 fixes the issue. 

Had to change the condition of the index check since needsPaging is strangely interconnected with the search.

**Comment by solverat** [comment]
@mattamon This may fix the `error_object_change_children_sort_to_index` error, but in my case there is another one.

- change object folder sorting to manual
- try to rearrange objects
- message: `element_cannot_be_moved_because_target_is_paginated`

Happening here (`record.needsPaging` is always `true`):

https://github.com/pimcore/admin-ui-classic-bundle/blob/c68397e4e4fa83d6179e1a04b75fc28f2747a4ac/public/js/pimcore/object/tree.js#L365-L366

**Comment by mattamon** [comment]
> [@mattamon](https://github.com/mattamon) This may fix the `error_object_change_children_sort_to_index` error, but in my case there is another one.
> 
> * change object folder sorting to manual
> * try to rearrange objects
> * message: `element_cannot_be_moved_because_target_is_paginated`
> 
> Happening here (`record.needsPaging` is always `true`):
> 
> [admin-ui-classic-bundle/public/js/pimcore/object/tree.js](https://github.com/pimcore/admin-ui-classic-bundle/blob/c68397e4e4fa83d6179e1a04b75fc28f2747a4ac/public/js/pimcore/object/tree.js#L365-L366)
> 
> Lines 365 to 366 in [c68397e](/pimcore/admin-ui-classic-bundle/commit/c68397e4e4fa83d6179e1a04b75fc28f2747a4ac)
> 
>  if(((newParent.needsPaging) || (newParent.childNodes.length > pimcore.settings['object_tree_paging_limit'])) && (newParent.data.sortBy == "index")){ 
>      pimcore.helpers.showNotification(t("error"), t("element_cannot_be_moved_because_target_is_paginated"), "error");

Of course this was checked somewhere else too :D I updated my PR :) Would you be so kind as to test it again? Thank you!

**Comment by solverat** [comment]
@mattamon Yes! Looks good to me!

**Comment by mattamon** [comment]
Closed by #723
