### ISSUE TITLE
[Bug] ManyToOne relation in readonly mode doesn't respect path formatter

### ISSUE THREAD

**Issue by limenet** [pimcore/admin-ui-classic-bundle#732]
Follow-up to #638. The changes introduced by #645 only work when the field is editable, yet when it's not, the nice path is returned via XHR yet is not displayed.

Editing:

![Image](https://github.com/user-attachments/assets/04b6f7a6-16f0-44c8-8bfc-4b785e1bf549)

`/element/get-nice-path`

![Image](https://github.com/user-attachments/assets/696d3d7e-d37c-47c5-93bb-36f166187625)

**Comment by blankse** [comment]
@limenet There is already a PR for this: https://github.com/pimcore/admin-ui-classic-bundle/pull/731

**Comment by limenet** [comment]
@blankse my bad, I only searched the open issues, thanks!
