### ISSUE TITLE
Pimcore doesn't allow to sort children by index

### ISSUE THREAD

**Issue by simonittensammer** [pimcore/admin-ui-classic-bundle#736]
Pimcore Version 11.4.1
admin-ui-classic-bundle Version 1.6.1

I selected "sort children by -> index (manual)" on the parent. When i try to drag and drop a dataobject to any other position under the parent, the following error is thrown:
`The element cannot be dragged on a paginated tree/folder with manual indexing (Sort by index). Please change the sorting method or use "Search & Move" option under the "Advanced" context menu of the target to move the elements.`

![Image](https://github.com/user-attachments/assets/ff0ce8eb-9530-4fe1-b10b-4d27497faafa)
![Image](https://github.com/user-attachments/assets/cb1532aa-14d6-4b8d-8995-5d07d55156b2)

**Comment by bramstroker** [comment]
Same issue for our clients which have updated to latest admin-ui-classic-bundle.
Think it is fixed with #722.
Seems like an idea to quickly release a new version as 1.6.1 is completely broken in this regard.

**Comment by kingjia90** [comment]
Thank you for reporting!

Closing as resolved, considering it fixed by https://github.com/pimcore/admin-ui-classic-bundle/issues/722 as also noted by @bramstroker 
Feel free to reopen a new issue if the problem still occurs, later today the `1.6.2` would be released.
