### ISSUE TITLE
[Bug] Using a `table` type field in a classification store does not work

### ISSUE THREAD

**Issue by mcop1** [pimcore/admin-ui-classic-bundle#737]
Leads to an error when you try to add the classification store to the data object:
![Image](https://github.com/user-attachments/assets/f3d8814e-1f3f-4709-8341-80fe2e779173)

How to reproduce:

1.) Add a table type field as key
![Image](https://github.com/user-attachments/assets/647640b9-8b1c-4a2c-a451-2d0c308f5505)
2.) Add the key to a group, e.g. `Dimensions`
3.) Go to a data object
4.) Try to add the cstore
5.) Nothing happens, check the console, find the error (see screenshot above)

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/17794
