### ISSUE TITLE
[Bug] Moving object directly onto folder without the folder being loaded resulted in the object never getting updated and moved

### ISSUE THREAD

**Issue by mattamon** [pimcore/admin-ui-classic-bundle#756]
Based on this PR https://github.com/pimcore/admin-ui-classic-bundle/pull/469/files#diff-3b41334b430020814d1a30721473a6d8647e88045cb572be36931f80d28522f2L277 where a check was removed, the update function was never called, thus not updating or moving the object.

**Comment by kingjia90** [comment]
Resolved by #757
