### ISSUE TITLE
Replace Request::get with explicit input sources

### ISSUE THREAD

**Issue by kingjia90** [pimcore/admin-ui-classic-bundle#771]
Related https://github.com/pimcore/pimcore/issues/14138

**Comment by kingjia90** [comment]
![Image](https://github.com/user-attachments/assets/0ccbd512-3c5a-484e-b03c-29be541f4629)

It may take a little while, should it be done or skipped?

**Comment by fashxp** [comment]
would say we won't do that anytime soon, WDYT?
