### ISSUE TITLE
[BUG]: Video Element not working

### ISSUE THREAD

**Issue by foxgreek** [pimcore/admin-ui-classic-bundle#784]
Version: 1.6.3

When you try to edit a video you will get this error:
![Image](https://github.com/user-attachments/assets/a0cadec4-6e80-4b89-ad5c-987ee6f4e736)

You can reproduce this bug in the demo instance with the default video areabrick

**Comment by blankse** [comment]
@foxgreek I created a PR: https://github.com/pimcore/admin-ui-classic-bundle/pull/785

**Comment by robertSt7** [comment]
fixed by #785
