### ISSUE TITLE
[Bug] Show in Tree not working

### ISSUE THREAD

**Issue by foxgreek** [pimcore/admin-ui-classic-bundle#787]
If you try to click **Show in Tree** in a data object, document or asset it won't open the corresponding tree.
You can reproduce it in the pimcore demo

**Comment by blankse** [comment]
@foxgreek It exists already a PR for this: https://github.com/pimcore/admin-ui-classic-bundle/pull/783

**Comment by foxgreek** [comment]
@blankse perfect!
