### ISSUE TITLE
[BUG] Show in tree is not working

### ISSUE THREAD

**Issue by atul-emico** [pimcore/admin-ui-classic-bundle#789]
On object edit page "Show in tree" is not working. In network tab Ajax request is successful, but process tree is not working. 

![Image](https://github.com/user-attachments/assets/cbfab2ec-0c9e-4807-b497-6880755dd4a9)

In further investigation it is found that "processTree" function in "vendor/pimcore/admin-ui-classic-bundle/public/js/pimcore/treenodelocator.js" file is having a issue.

```
var locateConfig = globalState.locateConfigs[globalState.currentTreeIndex];
var tree = locateConfig.tree;
var rootNode = tree.tree.getRootNode();
var rootNodeId = rootNode.getId();

// Tree root may be shifted to a subnode and the item to be shown
// is out of tree scope - don't continue if this is the case:
if (globalState.pathIds.indexOf(rootNodeId) == -1) {
    self.reportProcessTreeFailed();
    return;
}
```

In latest version 1.7.2 "rootNodeId" is of type number. Earlier it was of type "string". Because of this change 
`if (globalState.pathIds.indexOf(rootNodeId) == -1) ` condition is always true. So next code is not getting executed.

For testing purpose I tried to make a root node id as string and it is working fine.

`var rootNodeId = rootNode.getId().toString(); `

**Comment by blankse** [comment]
Already fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/783
