### ISSUE TITLE
[Bug][DataObject][Grid] Cannot filter for system columns path & key

### ISSUE THREAD

**Issue by fashxp** [pimcore/admin-ui-classic-bundle#79]
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/8792145/d55fba2b-fdd9-46af-bfcb-ec266fead9f6)

either remove filter feature, or fix filtering.

**Comment by robertSt7** [comment]
Escape `$filter[property]` [here](https://github.com/pimcore/admin-ui-classic-bundle/blob/49324a4330dab35571feab45d03851b9a01e62a0/src/Helper/GridHelperService.php#L345)

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/168
