### ISSUE TITLE
[Bug] list view for assets with non-admin user does not work

### ISSUE THREAD

**Issue by heigpa** [pimcore/admin-ui-classic-bundle#796]
**Steps to reproduce:**

- Login with superuser
- Open an asset folder
- Switch the view to the list view

**Actual behaviour:**

- Error message appears: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'key' in 'where clause'

**Expected behaviour:**

- Assets are shown in list view

**Environment:** 

- demo.pimcore.com

**Comment by la-lisa** [comment]
PR already there: #793
