### ISSUE TITLE
[Bug][Pimcore 11] User cannot setup 2FA

### ISSUE THREAD

**Issue by fashxp** [pimcore/admin-ui-classic-bundle#81]
### Pimcore version

11

### Steps to reproduce

- Open users profile
- click on `Setup Two Factor Authentication`
![image](https://github.com/pimcore/pimcore/assets/8792145/8fcd8109-047f-442d-bf1b-e9491e67461c)

--> user gets logged out.

**Comment by kingjia90** [comment]
Potential regression from https://github.com/pimcore/pimcore/pull/13909

The part of [popup ](https://github.com/pimcore/pimcore/pull/13909/files?w=1#diff-62e5f006cff984720e3dd79ab30f3bbe859e3cc5129f8146362265197810d510L62-L97) with the [QR code](https://github.com/pimcore/pimcore/pull/13909/files?w=1#diff-a70b6d2649c19a27bc3b189e3eb2379230166e3a5511495020c9dabc21f6a1b7L829-L866) is missing, while only the save & logout is there.

**Comment by kingjia90** [comment]
By digging a little bit, it seems that the behaviour got changed https://github.com/pimcore/pimcore/pull/13909#discussion_r1088749522 , probably something happened when rebasing here https://github.com/pimcore/pimcore/pull/13909#issuecomment-1407708576 as it was working on https://github.com/pimcore/pimcore/pull/13909#issuecomment-1406683977
